# Generated by Django 5.2.3 on 2025-07-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('jobtype', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('salary', models.TextField(max_length=122)),
                ('skills', models.CharField(max_length=122)),
                ('companyName', models.CharField(max_length=122)),
                ('website', models.TextField(max_length=122)),
            ],
        ),
    ]
