# Generated by Django 5.2.3 on 2025-07-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='confirm',
        ),
    ]
