# Generated by Django 5.2.3 on 2025-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_message_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='confirm',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
