# Generated by Django 5.2.3 on 2025-07-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
