# Generated by Django 5.2.3 on 2025-07-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_user_confirm_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='username',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='confirm',
            old_name='website',
            new_name='lname',
        ),
    ]
